Update ServerInstallation.md
exoframejs/exoframe-website pull request #2
Opened 2020-04-27 18:17 UTC by FDiskas

Updated readme in case exoframejs/exoframe-server#39 will be merged

2020-04-28 18:12 UTC, yamalight requested changes
Looks almost prefect, just a few minor changes please!

2020-04-28 18:12 UTC, yamalight commented on contents/ServerInstallation.md
> +### Automatic installation
Let's call it "Guided installation" since it's not really automatic 🤔

2020-04-28 18:12 UTC, yamalight commented on contents/ServerInstallation.md
> +Available parameters:
This should be in a separate section preceded by command to dowload `install.sh` first.

2020-04-30 06:03 UTC, FDiskas commented
Duplicate on main repo.

2020-05-11 15:59 UTC, merged